version: "3.8"
services:
  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
      - SEQ_API_LISTENURIS=http://127.0.0.1:5430
    volumes:
      - seq_data:/data
    ports:
      - "5340:5340"

volumes:
  seq_data:
